name: Build

on:
  push:
    branches:
      - main
      - master
      - devel
  pull_request:
    branches:
      - main
      - master
      - devel

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc \
            g++ \
            libgomp1 \
            libhdf5-dev \
            libgsl-dev \
            make \
            cmake \
            pkg-config

      - name: Compile
        run: |
          echo "Compiling..."
          make

      - name: Standard run
        run: |
          echo "Running standard parameters..."
          sh run.sh
