name: Testing

on:
  push:
    branches:
      - main
      - master
      - devel
  pull_request:
    branches:
      - main
      - master
      - devel

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."

      - name: Compile
        run: |
          echo "Compiling..."
