name: Static analysis

on:
  push:
    branches:
      - main
      - master
      - devel
  pull_request:
    branches:
      - master
      - master
      - devel

jobs:
  Inspect_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Download and run cloc
        run: |
          curl -s https://raw.githubusercontent.com/AlDanial/cloc/master/cloc > cloc
          chmod +x cloc
          ./cloc --version
          ./cloc $(git ls-files)